Project Sainseni {
    database_type: 'PostgreSQL'
    Note: '''
        Sainseni
    '''
}

Table users as U {
    id int [pk, increment]
    name text
    email text
    email_verified timestamp
    image text
    created_at timestamp
    updated_at timestamp
}

Table accounts {
    id int [pk]
    type text
    provider text
    provider_account_id text
    refresh_token text
    access_token text
    expires_at int
    token_type text
    scope text
    id_token text
    sesstion_state text
    created_at timestamp
    updated_at timestamp
    user_id int [ref: > users.id]
}

Table sessions {
    id int [pk]
    session_token text
    expires timestamp
    user_id int [ref: > users.id]
}

Table verification_tokens {
    identifier text
    token text
    expires timestamp
}