#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo 'Rebasing your project before pushing...'

# Rebase
git pull --rebase origin main

# Check Conflict
if [ $? -eq 0 ]; then
    echo '🎉 No conflict found: commiting this now.... ✨🚀🏄‍♂️🍻'
else
    echo '🔨❌ Yoo, you have a conflict in your code. Check your git status 🔨❌ Run git status, add changes and try commit again.';
    false;
fi
```