#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Rebase
echo 'Rebasing your project before pushing...'
git pull --rebase origin main

# Check
echo '🏗️👷 Checking your project before pushing'
echo 'please be patient, this may take a while...'

# Check ESLint Standards
pnpx lint-staged ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check your linter 🔨❌ Run pnpm lint, add changes and try commit again.';
    false;
)

# Test Build
pnpm build ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check your build 🔨❌ Run pnpm build, add changes and try commit again.';
    false;
)

# Run test
pnpm test ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check your test 🔨❌ Run pnpm test, add changes and try commit again.';
    false;
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'