name: Deploy Preview
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7.33.1
                  run_install: true
            - name: Lint
              run: pnpm lint
            - name: Build
              run: pnpm build
            - name: Test
              run: pnpm test
    build_dbdocs:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7.33.1
                  run_install: false
            - name: Install dbdocs global
              run: pnpm add -g dbdocs
            - name: Build DBDocs
              run: dbdocs build ./docs/database.dbml --project=Sainseni --password=${{ secrets.DBDOCS_PASSWORD }} --output=./docs

    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        needs: build
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7.33.1
                  run_install: false

            - name: Install Vercel CLI with pnpm
              run: pnpm add -g vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

            - name: Set output URL
              id: vercel
              run: echo "url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT

            - name: Comment on Pull Request
              uses: peter-evans/create-or-update-comment@v2
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      Preview URL: ${{ steps.vercel.outputs.url }}
