name: PR
env:
    NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID_STAGING }}
    GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET_STAGING }}
    GOOGLE_CLIENT_ID: ${{ secrets.OAUTH_GOOGLE_CLIENT_ID_STAGING }}
    GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH_GOOGLE_CLIENT_SECRET_STAGING }}
on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 8.15.5
                  run_install: true
            - name: Lint
              run: pnpm lint
            - name: Build
              run: pnpm build
            - name: Test
              run: pnpm test

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 8.15.5
                  run_install: false

            - name: Install Vercel CLI with pnpm
              run: pnpm add -g vercel@latest

            - name: Set env Vercel
              run: |
                  echo -n "${{ secrets.DATABASE_URL_STAGING }}" | vercel env add DATABASE_URL preview --token=${{ secrets.VERCEL_TOKEN }} || true 
                  echo -n "${{ secrets.OAUTH_GITHUB_CLIENT_ID_STAGING }}" | vercel env add GITHUB_CLIENT_ID preview --token=${{ secrets.VERCEL_TOKEN }} || true
                  echo -n "${{ secrets.OAUTH_GITHUB_CLIENT_SECRET_STAGING }}" | vercel env add GITHUB_CLIENT_SECRET preview --token=${{ secrets.VERCEL_TOKEN }} || true
                  echo -n "${{ secrets.OAUTH_GOOGLE_CLIENT_ID_STAGING }}" | vercel env add GOOGLE_CLIENT_ID preview --token=${{ secrets.VERCEL_TOKEN }} || true
                  echo -n "${{ secrets.OAUTH_GOOGLE_CLIENT_SECRET_STAGING }}" | vercel env add GOOGLE_CLIENT_SECRET preview --token=${{ secrets.VERCEL_TOKEN }} || true

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt

            - name: Set output URL
              id: vercel
              run: echo "url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT

            - name: Comment on Pull Request
              uses: peter-evans/create-or-update-comment@v2
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      Preview URL: ${{ steps.vercel.outputs.url }}
