name: Vercel Preview Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 8.15.5
                  run_install: true
            - name: Lint
              run: pnpm lint
            - name: Build
              run: pnpm build
            - name: Test
              run: pnpm test

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 8.15.5
                  run_install: false

            - name: Install Vercel CLI with pnpm
              run: pnpm add -g vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

            - name: Set output URL
              id: vercel
              run: |
                  echo "::set-output name=url::$(vercel --token=${{ secrets.VERCEL_TOKEN }} output --environment=preview --json | jq -r '.[0].url')"

            - name: Set Vercel URL as an output
              run: echo "URL=${{ steps.vercel.outputs.url }}" >> $GITHUB_ENV

            - name: Comment on Pull Request
              uses: actions/github-script@v4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      github.issues.createComment({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          body: 'Preview deployment is live at ${{ steps.vercel.outputs.url }}'
                      })
