name: Staging
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches:
            - main
jobs:
    deploy:
        environment:
            name: 'Staging'
            url: ${{ steps.vercel.outputs.url }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 8.15.5
                  run_install: false

            - name: Install Vercel CLI with pnpm
              run: pnpm add -g vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt

            - name: Set output URL
              id: vercel
              run: echo "url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT

            - name: Set vercel alias URL staging
              run: vercel alias set ${{ steps.vercel.outputs.url }} ${{ secrets.VERCEL_STAGING_DOMAIN }} --token=${{ secrets.VERCEL_TOKEN }}

            - name: Create Deployment
              id: create_deployment
              uses: octokit/request-action@v2.x
              with:
                  route: POST /repos/${{ github.repository }}/deployments
                  ref: ${{ github.sha }}
                  payload: '{"ref":"${{ github.ref }}","auto_merge":false,"required_contexts":[]}'
                  mediaType: '{"accept":"application/vnd.github.ant-man-preview+json,application/vnd.github.flash-preview+json"}'
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set Deployment Status
              uses: octokit/request-action@v2.x
              with:
                  route: POST /repos/${{ github.repository }}/deployments/${{ steps.create_deployment.outputs.deployment_id }}/statuses
                  token: ${{ secrets.GITHUB_TOKEN }}
                  mediaType: '{"accept":"application/vnd.github.ant-man-preview+json,application/vnd.github.flash-preview+json"}'
                  payload: '{"state":"success","environment_url":"${{ steps.vercel.outputs.url }}"}'
