name: Staging
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches:
            - main
jobs:
    deploy:
        environment:
            name: 'Staging'
            url: ${{ steps.vercel.outputs.url }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 8.15.5
                  run_install: false

            - name: Install Vercel CLI with pnpm
              run: pnpm add -g vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt

            - name: Set output URL
              id: vercel
              run: echo "url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT

            - name: Set vercel alias URL staging
              run: vercel alias set ${{ steps.vercel.outputs.url }} ${{ secrets.VERCEL_STAGING_DOMAIN }} --token=${{ secrets.VERCEL_TOKEN }}
